Python Client: Require Python >= 3.7
Following the introduction of pyproject.toml in 6ed8b33 (Python Client: Support
publishing as sdist & wheel), installing the project using python 3.6 is
not supported, it leads to having a package called "UNKNOWN" being generated.

For this reason, this commit partially reverts a6701a0 (Server / Python Client:
Fix python minimum version requiring 3.6) and require Python >= 3.7 for
the client.

Attempting to install the client using Python < 3.7 will now report a message
like the following:

$ pip install python_client/
Processing ./python_client
  Installing build dependencies ... done
  Getting requirements to build wheel ... done
  Installing backend dependencies ... done
  Preparing metadata (pyproject.toml) ... done
ERROR: Package 'unknown' requires a different Python: 3.6.15 not in '>=3.7'